Repository jupyter-book/jupyterlab-myst, pull requests merged in 2023-09, with the labels that each got.

#183 feat: use latest MySTJS
  package.json
  src/myst.ts
  src/renderers.tsx
  src/taskItem.tsx
  src/widget.tsx
  yarn.lock
Labels: enhancement

#118 ⚛️ Render HTML directly
  package.json
  src/MySTMarkdownCell.tsx
  src/SanitizerProvider.tsx
  src/mime.tsx
  src/myst.ts
  src/renderers.tsx
  src/widget.tsx
  style/jupyterlab-typography.css
  yarn.lock
Labels: enhancement

#190 ci: temporarily disable browser check
  .github/workflows/build.yml
  .prettierignore
Labels: maintenance

#186 🎨 Update HTML styles for buttons, kbd, etc.
  src/renderers.tsx
  style/preflight.css
Labels: bug

#187 🚴‍♀️ Refactor task-item
  src/taskItem.tsx
Labels: maintenance
