Repository jupyter-book/jupyterlab-myst, pull requests merged in 2023-03, with the labels that each got.

#108 🐛 Revive showing errors
  src/inlineExpression.tsx
Labels: bug

#110 🐛 Fix widgets so they don't render as text
  src/inlineExpression.tsx
Labels: bug

#113 feat: react to cell trust
  .github/workflows/build.yml
  examples/inline-interactivity.ipynb
  jupyter-config/jupyter_server_config.d/jupyterlab-myst.json
  jupyterlab_myst/__init__.py
  jupyterlab_myst/notary.py
  pyproject.toml
  requirements-test.txt
  src/MySTMarkdownCell.tsx
  tests/notebooks/inline-markdown.ipynb
  tests/notebooks/rich-code.ipynb
  tests/notebooks/simple-code.ipynb
  tests/notebooks/simple-markdown.ipynb
  tests/test_trust.py
Labels: enhancement

#120 :link: Ignore Binder links in link-checker
  .github/workflows/build.yml
Labels: maintenance

#116 👩🏻‍🎨 Move to Jupyter-based styles
  src/MySTMarkdownCell.tsx
  src/actions.ts
  src/myst.ts
  style/jupyterlab-typography.css
  tailwind.config.js
  ui-tests/tests/notebook-run.spec.ts-snapshots/Notebook-Run-Run-Notebook-and-capture-cell-outputs-1-linux.png
Labels: enhancement

#117 🛩👩‍✈️💺 Remove almost all preflight css
  style/preflight.css
Labels: enhancement

#119 :police_officer: Executing Markdown cells should set trust
  src/actions.ts
Labels: bug

#121 ✅ Editable task lists
  .eslintrc.js
  README.md
  images/tasklists-in-jupyterlab.gif
  package.json
  src/renderers.tsx
  src/taskItem.tsx
  style/tailwind.css
  yarn.lock
Labels: enhancement

#122 :camera: update integration snapshots
  ui-tests/tests/notebook-run.spec.ts-snapshots/Notebook-Run-Run-Notebook-and-capture-cell-outputs-1-linux.png
Labels: maintenance

#123 🃏 Apply classnames for links
  src/links.tsx
Labels: bug

#131 🧹🧹 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: maintenance
