Repository jupyter-book/jupyterlab-myst, pull requests merged in 2024-02, with the labels that each got.

#203 wip: update with copier
  .copier-answers.yml
  .eslintignore
  .eslintrc.js
  .github/workflows/binder-on-pr.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/update-integration-tests.yml
  .prettierignore
  .prettierrc
  .stylelintignore
  .stylelintrc
  .yarnrc.yml
  LICENSE
  RELEASE.md
  binder/environment.yml
  package.json
  pyproject.toml
  setup.py
  src/actions.ts
  src/citations.tsx
  src/images.ts
  src/links.tsx
  src/metadata.ts
  src/taskItem.tsx
  src/widget.tsx
  style/base.css
  style/index.css
  style/tailwind.css
  tsconfig.json
  tsconfig.test.json
  ui-tests/README.md
  ui-tests/package.json
  yarn.lock
Labels: maintenance

#210 chore: update lockfile for node18
  ui-tests/yarn.lock
Labels: maintenance

#211 maint: update snapshots
  ui-tests/tests/notebook-run.spec.ts-snapshots/Notebook-Run-Run-Notebook-and-capture-cell-outputs-1-linux.png
Labels: maintenance

#202 fix: line number is now human-readable (1 indexed)
  src/taskItem.tsx
Labels: bug

#212 maint: update snapshots
  ui-tests/tests/notebook-run.spec.ts-snapshots/Notebook-Run-Run-Notebook-and-capture-cell-outputs-1-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#214 refactor: reorganise extension files
  package.json
  src/MySTMarkdownCell.tsx
  src/__tests__/jupyterlab_myst.spec.ts
  src/actions.ts
  src/components/index.tsx
  src/components/inlineExpression.tsx
  src/components/listItem.tsx
  src/metadata.ts
  src/mime.tsx
  src/myst.ts
  src/providers/index.tsx
  src/providers/sanitizer.tsx
  src/providers/taskItem.tsx
  src/providers/userExpressions.tsx
  src/renderers.tsx
  src/roles.ts
  src/transforms/citations.ts
  src/transforms/images.ts
  src/transforms/index.ts
  src/transforms/links.tsx
  src/types.ts
  src/userExpressions.ts
  src/widget.tsx
  tsconfig.json
  yarn.lock
Labels: maintenance

#215 ENH: update theme
  .github/workflows/build.yml
  package.json
  src/__tests__/jupyterlab_myst.spec.ts
  src/components/listItem.tsx
  src/index.ts
  src/myst.ts
  src/renderers.tsx
  src/types.ts
  src/userExpressions.ts
  src/widget.tsx
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/files-run.spec.ts
  ui-tests/tests/files-run.spec.ts-snapshots/File-Run-View-Markdown-file-and-render-result-1-linux.png
  ui-tests/tests/files/myst_tests.md
  ui-tests/tests/notebook-run.spec.ts-snapshots/Notebook-Run-Run-Notebook-and-capture-cell-outputs-1-linux.png
  ui-tests/tests/notebooks/myst_tests.ipynb
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#217 FIX: inherit Jupyter styles for buttons
  package.json
  style/jupyterlab-typography.css
  style/preflight.css
  ui-tests/tests/files-run.spec.ts-snapshots/File-Run-View-Markdown-file-and-render-result-1-linux.png
  ui-tests/tests/notebook-run.spec.ts-snapshots/Notebook-Run-Run-Notebook-and-capture-cell-outputs-1-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: bug

#223 fix: don't render list items as task items
  src/components/listItem.tsx
Labels: bug
